apiVersion: v1
kind: Service
metadata:
  name: customer-srv
  labels:
    name: srv
    app: customer-service
spec:
  type: NodePort
  selector:
    name: customer-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
   
