apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
    app: db
spec:
  selector:
    name: mysql
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

